### ISSUE TITLE
膜拜大佬

### ISSUE THREAD

**Issue by iammsf** [Seraphli/SHENZHEN-I-O-Walkthrough#1]
滿世界找不到遊戲攻略，卡關了很難受，沒想到在Gayhub上找到了哈哈哈哈

**Comment by Seraphli** [comment]
Gayhub可还行哈哈…并不是大佬啦…其实steam社区上有攻略…有些解法可能会比我的要好一些

**Comment by iammsf** [comment]
哈哈，平時不喜歡翻社區，東西太雜很難找。Google上搜攻略可是只此一家哦

**Comment by Seraphli** [comment]
:smiley: 有帮助到就好
